# Generated by Django 4.2.14 on 2024-07-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excel_Certif_Input',
            new_name='ExcelCertifInput',
        ),
    ]
