# Generated by Django 4.2.14 on 2024-07-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_rename_excel_certif_input_excelcertifinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelcertifinput',
            name='excelfile',
            field=models.FileField(upload_to='excelfiles/'),
        ),
    ]
