# Generated by Django 4.2.14 on 2024-07-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_excelcertifinput_excelfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelcertifinput',
            name='column_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
